### ISSUE TITLE
[BUG] 示例错误 "model": "model": "ms-marco-MiniLM-L-6-v2" 

### ISSUE THREAD

**Issue by NieAnSHOW** [sugarforever/peanut-shell#1]
在 README.md 文件中的 Rerank documents :69
"model": "model": "ms-marco-MiniLM-L-6-v2" 示例错误，导致本地运行调试报错
订正为 "model": "ms-marco-MiniLM-L-6-v2" 即可

**Comment by sugarforever** [comment]
感谢反馈，已修正 https://github.com/sugarforever/peanut-shell/pull/2
